ActionManager {
 Actions {
  Action MrFrost_OpenInfoMenu {
   InputSource InputSourceSum "{7FA1C3D2E4B51300}" {
    Sources {
     InputSourceCombo "{7FA1C3D2E4B51310}" {
      FilterPreset "select"
      Sources {
       InputSourceValue "{7FA1C3D2E4B51301}" {
        Input "keyboard:KC_F11"
       }
      }
     }
    }
   }
  }
  Action MrFrost_OpenReportMenu {
   InputSource InputSourceSum "{7FA1C3D2E4B51305}" {
    Sources {
     InputSourceCombo "{7FA1C3D2E4B51312}" {
      FilterPreset "select"
      Sources {
       InputSourceValue "{7FA1C3D2E4B51306}" {
        Input "keyboard:KC_F10"
       }
      }
     }
    }
   }
  }
  Action MrFrost_ReportSubmit {
   InputSource InputSourceSum "{7FA1C3D2E4B51307}" {
    Sources {
     InputSourceCombo "{7FA1C3D2E4B5131E}" {
      FilterPreset "hold"
      Sources {
       InputSourceValue "{7FA1C3D2E4B5131F}" {
        Input "keyboard:KC_RETURN"
        Filter InputFilterHoldOnce "{7FA1C3D2E4B51320}" {
         HoldDuration 1000
        }
       }
      }
     }
     InputSourceCombo "{7FA1C3D2E4B5131B}" {
      FilterPreset "hold"
      Sources {
       InputSourceValue "{7FA1C3D2E4B5131C}" {
        Input "gamepad0:right_trigger"
        Filter InputFilterHoldOnce "{7FA1C3D2E4B5131D}" {
         HoldDuration 1000
        }
       }
      }
     }
    }
   }
  }
  Action MrFrost_MenuDiscord {
   InputSource InputSourceSum "{7FA1C3D2E4B51303}" {
    Sources {
     InputSourceCombo "{7FA1C3D2E4B51311}" {
      FilterPreset "select"
      Sources {
       InputSourceValue "{7FA1C3D2E4B51304}" {
        Input "keyboard:KC_D"
       }
      }
     }
     InputSourceCombo "{7FA1C3D2E4B51318}" {
      FilterPreset "select"
      Sources {
       InputSourceValue "{7FA1C3D2E4B51319}" {
        Input "gamepad0:y"
       }
      }
     }
    }
   }
  }
 }
 Contexts {
  ActionContext MrFrostContext {
   ActionRefs +{
    "MrFrost_OpenInfoMenu"
    "MrFrost_OpenReportMenu"
   }
  }
  ActionContext CharacterGeneralContext {
   ActionRefs +{
    "MrFrost_OpenInfoMenu"
    "MrFrost_OpenReportMenu"
   }
  }
  ActionContext MenuContext {
   ActionRefs +{
    "MrFrost_MenuDiscord"
    "MrFrost_ReportSubmit"
   }
  }
 }
}
