MenuManager {
 MenuPresets {
  MenuPreset MrFrost_InfoMenu {
   Layout "{7FA1C3D2E4B50602}UI/layouts/MrFrost/MrFrostMenuFrame.layout"
   Class "MrFrost_InfoMenuUI"
  }
  MenuPreset MrFrost_ReportMenu {
   Layout "{7FA1C3D2E4B50602}UI/layouts/MrFrost/MrFrostMenuFrame.layout"
   Class "MrFrost_ReportUI"
  }
 }
}
