SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{7FA1C3D2E4B51400}" {
   m_sName "MrFrost"
   m_sDisplayName "MrFrost"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{7FA1C3D2E4B51401}" {
     m_sActionName "MrFrost_OpenInfoMenu"
     m_sDisplayName "Info Menu"
     m_sPreset "select"
    }
    SCR_KeyBindingEntry "{7FA1C3D2E4B51402}" {
     m_sActionName "MrFrost_OpenReportMenu"
     m_sDisplayName "Report"
     m_sPreset "select"
    }
   }
  }
 }
}
