MrFrost_ReportConfig {
 m_bEnabled 1
 m_bAllowBugReports 1
 m_bAllowPlayerReports 1
 m_fNearbyRadius 300
 m_iCooldownSeconds 10
 m_iMaxDescription 1000
 m_MenuIconImageset "{3262679C50EF4F01}UI/Textures/Icons/icons_wrapperUI.imageset"
 m_sMenuIconName "feedback"
}
